steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cloud builds triggers create github build_wflowcreateproduct1 --included-files "wflowproductshandler-createproduct1/*" --repo-name=chrono-productsworkflows --repo-owner=rbannist --branch-pattern=$BRANCH_NAME
        cloud builds triggers create github build_wflowdeleteproduct1 --included-files "wflowproductshandler-deleteproduct1/*" --repo-name=chrono-productsworkflows --repo-owner=rbannist --branch-pattern=$BRANCH_NAME
